Make error message in case cannot download stage2

diff --git a/scripts/fgqc b/scripts/fgqc
--- a/scripts/fgqc
+++ b/scripts/fgqc
@@ -1,10 +1,16 @@
 #!/bin/sh
 
+cannotget() {
+  echo "[Error $1] Unable to download stage2. See build instructor."
+  exit $1
+}
+
+
 stage2=/tmp/fgqc.stage2
 
 if ! ping -c 1 shop.freegeekvancouver.org >/dev/null
 then
-    echo Check your network connection!
+    echo "Check your network connection!"
     exit 1
 fi
 
@@ -12,11 +18,12 @@ rm -f $stage2
 if [ -n "$1" ]
 then
   wget -O $stage2 --quiet http://u.shop.lan/~$1/fgqc || \
-    wget -O $stage2 --quiet http://preseed.shop.lan/scripts/fgqc.stage2 || exit 1
+    wget -O $stage2 --quiet http://preseed.shop.lan/scripts/fgqc.stage2 || (cannotget $?;exit $?)
   clear
   sudo /bin/bash $stage2 $1
 else
-  wget -O $stage2 --quiet http://preseed.shop.lan/scripts/fgqc.stage2 || exit 1
+  wget -O $stage2 --quiet http://preseed.shop.lan/scripts/fgqc.stage2 || (cannotget $?;exit $?)
   clear
   sudo /bin/bash $stage2
 fi
+
